server:
  port: 8081

spring:
  datasource:
    name: mysql_blog
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=UTC
      username: root
      password: root


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8

  #
#mybatis:
  #mapper-locations: classpath:mapper/*.xml


logging:
  level:
    root: warn
    lut.software.gavinoblog.mapper: info
    file: log/blog-pro.log
